export const ICON_NAME = {
  ADD: 'Add',
  ALERT_CIRCLE: 'AlertCircle',
  ARCHIVE: 'Archive',
  CALENDAR: 'Calendar',
  CHECKBOX_ACTIVE: 'CheckBoxActive',
  CHECKBOX_CIRCLE_ACTIVE: 'CheckBoxCircleActive',
  CHECKBOX_CIRCLE_INITIAL: 'CheckBoxCircleInitial',
  CHECKBOX_DISABLED: 'CheckBoxDisabled',
  CHECKBOX_INITIAL: 'CheckBoxInitial',
  CLOSE_ISSUE: 'CloseIssue',
  CLOSE_MILESTONE: 'CloseMilestone',
  DELETE_ICON: 'DeleteIcon',
  EDIT_ICON: 'EditIcon',
  EMOJI: 'Emoji',
  GITHUB: 'Github',
  LABEL: 'Label',
  MILESTONE: 'Milestone',
  NEXT: 'Next',
  OPEN_ISSUE: 'OpenIssue',
  OPEN_MILESTONE: 'OpenMilestone',
  PAPERCLIP: 'Paperclip',
  PREVIOUS: 'Previous',
  REFRESH_ICON: 'RefreshIcon',
  SEARCH: 'Search',
  SELECT: 'Select',
  X_SQUARE: 'XSquare',
} as const;

export const ICON_SIZE = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
} as const;
